kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: default
  labels:
    k8s-app: backend
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: backend
  template:
    metadata:
      name: backend
      labels:
        k8s-app: backend
    spec:
      containers:
        - name: node-app
          image: registry.digitalocean.com/bmemes/bm-back:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-envs-config        