name: production

on:
  push:
    branches: [ main ]

env:
  CLUSTER_NAME_FIRST: bmprod-k8s
  CLUSTER_NAME_SECOND: bmprod2-k8s
  IMAGE_NAME: registry.digitalocean.com/bmemes/bm-back

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm i
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Build container image
      run: docker build -t $IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DOCR
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push $IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DO kubeconfig with short-lived credentials (prod)
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 $CLUSTER_NAME_FIRST

      - name: Deploy to DO Kubernetes
        run: kubectl set image deployment/backend node-app=$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

      - name: Save DO kubeconfig with short-lived credentials (prod2)
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 $CLUSTER_NAME_SECOND

      - name: Deploy to DO Kubernetes
        run: kubectl set image deployment/backend node-app=$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
